.TH "flexibee-notify-customers" "1" "0.0.0" "Vítězslav Dvořák" "FlexiBee reminder"
.SH "NAME"
flexibee-inventarize - Send unsettled documents listing to customers by email
.br
.SH "SYNTAX"
flexibee-inventarize
.br

.SH "DESCRIPTION"
Send unsettled documents listing to customers by email
.br
.SH "OPTIONS"
\fB--help\fR
.br
		Output help information and exit.
.br

\fB--version\fR
.br
		Output version information and exit.
.br
.SH "FILES"
\fI/etc/flexibee/client.json
.br
/etc/\fRflexibee/reminder.json
.br
\fI/var/log\fR/syslog
.br
.SH "ENVIRONMENT VARIABLES"
None used
.br
.SH "EXAMPLES"
To run this program the standard way type:
.br

flexibee-customers-notify
.br
.SH "AUTHORS"
Vítezslav Dvořák <info@vitexsoftware.cz>
.br

.SH "SEE ALSO"
flexibee-reminder(2) flexibee-matcher(2) flexibee-client-config(2) flexibee-client-config-checker(2)
.br

