.TH "php-flexibee-debts" "1" "0.1.1" "Vítězslav Dvořák <info@vitexsoftware.cz>" "php-flexibee-tools"
.SH "NAME"
php-flexibee-debts - Check debts in flexibee 
.br
.SH "SYNTAX"
php-flexibee-debts
.br
.SH "DESCRIPTION"
Load default config file /etc/flexibee/reminder.json and try to print all debts found.
.br
in case of success return 0 exit code else exit code 1
.br
.SH "OPTIONS"
.SH "FILES"
\fI/etc/\fRflexibee/reminder.json
\fI/etc/\fRflexibee/client.json
.br

.SH "EXAMPLES"
To run this program the standard way type:
.br

php-flexibee-debts
.br

.SH "AUTHORS"
Vítězslav Dvořák <info@vitexsoftware.cz>
.br
.SH "SEE ALSO"
php-flexibee-reminder(2)
.br
