<?php

declare(strict_types=1);

/**
 * This file is part of the AbraFlexi Reminder package
 *
 * https://github.com/VitexSoftware/abraflexi-reminder
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Tests\AbraFlexi\Reminder;

use AbraFlexi\Reminder\RemindMailer;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-12-10 at 23:41:41.
 *
 * @no-named-arguments
 */
class RemindMailerTest extends \PHPUnit\Framework\TestCase
{
    protected RemindMailer $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Mailer();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \AbraFlexi\Reminder\Mailer::addItem
     *
     * @todo   Implement testAddItem().
     */
    public function testAddItem(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \AbraFlexi\Reminder\Mailer::getCss
     *
     * @todo   Implement testGetCss().
     */
    public function testGetCss(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \AbraFlexi\Reminder\Mailer::getCurrentMailSize
     *
     * @todo   Implement testGetCurrentMailSize().
     */
    public function testGetCurrentMailSize(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }
}
