<?php

namespace Tests\AbraFlexi\Reminder;

use AbraFlexi\Reminder\SmsByGnokii;
/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-12-10 at 23:41:42.
 */
class SmsByGnokiiTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var SmsByGnokii
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SmsByGnokii;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers AbraFlexi\Reminder\SmsByGnokii::sendMessage
     * @todo   Implement testSendMessage().
     */
    public function testSendMessage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
