<?php

namespace Tests\AbraFlexi\Reminder;

use AbraFlexi\Reminder\SmsByAxfone;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-12-10 at 23:41:42.
 */
class SmsByAxfoneTest extends \PHPUnit\Framework\TestCase
{

    /**
     * @var SmsByAxfone
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new SmsByAxfone;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }

    /**
     * @covers AbraFlexi\Reminder\SmsByAxfone::setup
     * @todo   Implement testSetup().
     */
    public function testSetup()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AbraFlexi\Reminder\SmsByAxfone::curlInit
     * @todo   Implement testCurlInit().
     */
    public function testCurlInit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AbraFlexi\Reminder\SmsByAxfone::callAxfoneApi
     * @todo   Implement testCallAxfoneApi().
     */
    public function testCallAxfoneApi()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AbraFlexi\Reminder\SmsByAxfone::sendSmsMessage
     * @todo   Implement testSendSmsMessage().
     */
    public function testSendSmsMessage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AbraFlexi\Reminder\SmsByAxfone::sendMessage
     * @todo   Implement testSendMessage().
     */
    public function testSendMessage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
}
