<?php

declare(strict_types=1);

/**
 * This file is part of the AbraFlexi Reminder package
 *
 * https://github.com/VitexSoftware/abraflexi-reminder
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Tests\AbraFlexi\Reminder;

use AbraFlexi\Reminder\Sms;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-12-10 at 23:41:42.
 */
class SmsTest extends \PHPUnit\Framework\TestCase
{
    protected Sms $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Sms();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \AbraFlexi\Reminder\Sms::getMessage
     *
     * @todo   Implement testGetMessage().
     */
    public function testGetMessage(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \AbraFlexi\Reminder\Sms::getNumber
     *
     * @todo   Implement testGetNumber().
     */
    public function testGetNumber(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \AbraFlexi\Reminder\Sms::setNumber
     *
     * @todo   Implement testSetNumber().
     */
    public function testSetNumber(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \AbraFlexi\Reminder\Sms::setMessage
     *
     * @todo   Implement testSetMessage().
     */
    public function testSetMessage(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \AbraFlexi\Reminder\Sms::unifyTelNo
     *
     * @todo   Implement testUnifyTelNo().
     */
    public function testUnifyTelNo(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \AbraFlexi\Reminder\Sms::sendMessage
     *
     * @todo   Implement testSendMessage().
     */
    public function testSendMessage(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }
}
