<?php

namespace Tests\AbraFlexi\Reminder;

use AbraFlexi\Reminder\SmsToAddress;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-12-10 at 23:41:42.
 */
class SmsToAddressTest extends \PHPUnit\Framework\TestCase
{

    /**
     * @var SmsToAddress
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new SmsToAddress('', 'PHPUnit test');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }
}
