<?php

declare(strict_types=1);

/**
 * This file is part of the AbraFlexi Reminder package
 *
 * https://github.com/VitexSoftware/abraflexi-reminder
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Tests\AbraFlexi\Reminder;

use AbraFlexi\Reminder\Upominac;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-12-10 at 23:40:56.
 *
 * @no-named-arguments
 */
class UpominacTest extends \PHPUnit\Framework\TestCase
{
    protected Upominac $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Upominac();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \AbraFlexi\Reminder\Upominac::getCustomersDebts
     *
     * @todo   Implement testGetCustomersDebts().
     */
    public function testGetCustomersDebts(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Reminder\Upominac::everythingPaidOff
     *
     * @todo   Implement testEverythingPaidOff().
     */
    public function testEverythingPaidOff(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Reminder\Upominac::enableCustomer
     *
     * @todo   Implement testEnableCustomer().
     */
    public function testEnableCustomer(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Reminder\Upominac::processAllDebts
     *
     * @todo   Implement testProcessAllDebts().
     */
    public function testProcessAllDebts(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Reminder\Upominac::processUserDebts
     *
     * @todo   Implement testProcessUserDebts().
     */
    public function testProcessUserDebts(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Reminder\Upominac::getCustomerScore
     *
     * @todo   Implement testGetCustomerScore().
     */
    public function testGetCustomerScore(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Reminder\Upominac::posliUpominku
     *
     * @todo   Implement testPosliUpominku().
     */
    public function testPosliUpominku(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Reminder\Upominac::processNotifyModules
     *
     * @todo   Implement testProcessNotifyModules().
     */
    public function testProcessNotifyModules(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Reminder\Upominac::processModules
     *
     * @todo   Implement testProcessModules().
     */
    public function testProcessModules(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Reminder\Upominac::getEvidenceDebts
     */
    public function testGetEvidenceDebts(): void
    {
        // typDokl must only be fetched for faktura-vydana; pohledavka records
        // can have null typDoklK which causes a TypeError in AbraFlexi\Relation
        $debts = $this->object->getEvidenceDebts('faktura-vydana');
        $this->assertIsArray($debts, 'getEvidenceDebts must return an array');

        // pohledavka must not throw even when some records lack typDoklK
        $debts2 = $this->object->getEvidenceDebts('pohledavka');
        $this->assertIsArray($debts2, 'getEvidenceDebts(pohledavka) must return an array without TypeError');
    }

    /**
     * @covers \AbraFlexi\Reminder\Upominac::getAllDebts
     */
    public function testGetAllDebts(): void
    {
        $debts = $this->object->getAllDebts();
        $this->assertIsArray($debts, 'getAllDebts must return an array');

        foreach ($debts as $debt) {
            $this->assertArrayHasKey('firma', $debt, 'Each debt must have a firma key');
            $this->assertArrayHasKey('zbyvaUhradit', $debt, 'Each debt must have a zbyvaUhradit key');
        }
    }

    /**
     * @covers \AbraFlexi\Reminder\Upominac::getCustomerList
     *
     * @todo   Implement testGetCustomerList().
     */
    public function testGetCustomerList(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Reminder\Upominac::formatTotals
     */
    public function testFormatTotals(): void
    {
        $this->assertEquals('10,10 CZK,1,20 EUR', Upominac::formatTotals(['CZK' => 10.1, 'EUR' => 1.2]));
    }
}
