<?php

declare(strict_types=1);

/**
 * This file is part of the AbraFlexi Reminder package
 *
 * https://github.com/VitexSoftware/abraflexi-reminder
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Tests\AbraFlexi\Reminder;

use AbraFlexi\Reminder\Upominac;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-12-10 at 23:40:56.
 *
 * @no-named-arguments
 */
class UpominacTest extends \Tests\AbraFlexi\RWTest
{
    protected Upominac $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Upominac();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \AbraFlexi\Reminder\Upominac::getCustomersDebts
     *
     * @todo   Implement testGetCustomersDebts().
     */
    public function testGetCustomersDebts(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \AbraFlexi\Reminder\Upominac::everythingPaidOff
     *
     * @todo   Implement testEverythingPaidOff().
     */
    public function testEverythingPaidOff(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \AbraFlexi\Reminder\Upominac::enableCustomer
     *
     * @todo   Implement testEnableCustomer().
     */
    public function testEnableCustomer(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \AbraFlexi\Reminder\Upominac::processAllDebts
     *
     * @todo   Implement testProcessAllDebts().
     */
    public function testProcessAllDebts(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \AbraFlexi\Reminder\Upominac::processUserDebts
     *
     * @todo   Implement testProcessUserDebts().
     */
    public function testProcessUserDebts(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \AbraFlexi\Reminder\Upominac::getCustomerScore
     *
     * @todo   Implement testGetCustomerScore().
     */
    public function testGetCustomerScore(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \AbraFlexi\Reminder\Upominac::posliUpominku
     *
     * @todo   Implement testPosliUpominku().
     */
    public function testPosliUpominku(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \AbraFlexi\Reminder\Upominac::processNotifyModules
     *
     * @todo   Implement testProcessNotifyModules().
     */
    public function testProcessNotifyModules(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \AbraFlexi\Reminder\Upominac::processModules
     *
     * @todo   Implement testProcessModules().
     */
    public function testProcessModules(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \AbraFlexi\Reminder\Upominac::getEvidenceDebts
     *
     * @todo   Implement testGetEvidenceDebts().
     */
    public function testGetEvidenceDebts(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \AbraFlexi\Reminder\Upominac::getAllDebts
     *
     * @todo   Implement testGetAllDebts().
     */
    public function testGetAllDebts(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \AbraFlexi\Reminder\Upominac::getCustomerList
     *
     * @todo   Implement testGetCustomerList().
     */
    public function testGetCustomerList(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \AbraFlexi\Reminder\Upominac::formatTotals
     */
    public function testFormatTotals(): void
    {
        $this->assertEquals('10,10 CZK,1,20 EUR', Upominac::formatTotals(['CZK' => 10.1, 'EUR' => 1.2]));
    }
}
