debian/conf/composer.json       usr/lib/abraflexi-reminder/
src/*.php           	        usr/lib/abraflexi-reminder/

src/FlexiPeeHP/Reminder/Mailer.php      usr/lib/abraflexi-reminder/Reminder/
src/FlexiPeeHP/Reminder/PDFPage.php     usr/lib/abraflexi-reminder/Reminder/
src/FlexiPeeHP/Reminder/Upominac.php    usr/lib/abraflexi-reminder/Reminder/
src/FlexiPeeHP/Reminder/Upominka.php    usr/lib/abraflexi-reminder/Reminder/

src/FlexiPeeHP/Reminder/Notifier/ByEmail.php               usr/lib/abraflexi-reminder/Reminder/Notifier

bin/abraflexi-debts  		usr/bin/
bin/abraflexi-inventarize  	usr/bin/
bin/abraflexi-reminder		usr/bin/
bin/abraflexi-reminder-init      usr/bin/
debian/conf/reminder.json       etc/abraflexi/
i18n/cs_CZ/LC_MESSAGES/*.mo     usr/share/locale/cs_CZ/LC_MESSAGES
i18n/en_US/LC_MESSAGES/*.mo     usr/share/locale/en_US/LC_MESSAGES
abraflexi-reminder.svg		usr/share/icons/hicolor/scalable/apps

debian/io.github.vitexsoftware.abraflexi_reminder.metainfo.xml   usr/share/metainfo/

