#!/bin/sh
# postinst script for abraflexi-reminder
db_get composer/WEB_USER
WEBUSER=$RET
set -e

    if [ "$1" = "configure" ]; then

    . /usr/share/debconf/confmodule

    fi

su - $WEBUSER -s /bin/bash -c 'COMPOSER_HOME="/var/lib/composer" composer  -o require listonoska/api -d /usr/lib/abraflexi-reminder/'
su - $WEBUSER -s /bin/bash -c 'COMPOSER_HOME="/var/lib/composer" composer  -o require spipu/html2pdf -d /usr/lib/abraflexi-reminder/'

#DEBHELPER#

exit 0
