debian/conf/composer.json       usr/lib/abraflexi-reminder/
src/*.php           	        usr/share/abraflexi-reminder/

src/AbraFlexi/Reminder/InvoiceRecievedConfirmation.php  usr/lib/abraflexi-reminder/Reminder/
src/AbraFlexi/Reminder/InvoiceRecievingConfirmation.php usr/lib/abraflexi-reminder/Reminder/
src/AbraFlexi/Reminder/RemindMailer.php                 usr/lib/abraflexi-reminder/Reminder/
src/AbraFlexi/Reminder/PaymentRecievedConfirmation.php  usr/lib/abraflexi-reminder/Reminder/
src/AbraFlexi/Reminder/PDFPage.php                      usr/lib/abraflexi-reminder/Reminder/
src/AbraFlexi/Reminder/SentPaymentConfirmation.php      usr/lib/abraflexi-reminder/Reminder/
src/AbraFlexi/Reminder/Upominac.php                     usr/lib/abraflexi-reminder/Reminder/
src/AbraFlexi/Reminder/Upominka.php                     usr/lib/abraflexi-reminder/Reminder/
src/AbraFlexi/Reminder/Notifier/ByEmail.php             usr/lib/abraflexi-reminder/Reminder/Notifier

bin/abraflexi-show-debts        usr/bin/
bin/abraflexi-inventarize  	usr/bin/
bin/abraflexi-reminder  	usr/bin/
bin/abraflexi-reminder-init  	usr/bin/
bin/abraflexi-reminder-clean-labels usr/bin/

i18n/cs_CZ/LC_MESSAGES/*.mo     usr/share/locale/cs_CZ/LC_MESSAGES
i18n/en_US/LC_MESSAGES/*.mo     usr/share/locale/en_US/LC_MESSAGES
abraflexi-reminder.svg		usr/share/icons/hicolor/scalable/apps

debian/io.github.vitexsoftware.abraflexi_reminder.metainfo.xml   usr/share/metainfo/

template.env				etc/abraflexi-reminder
