#!/bin/sh
# postinst script for abraflexi-reminder
set -e

if [ "$1" = "configure" ]; then
    cat /usr/lib/abraflexi-reminder/composer.json | jq '.require += {"deb/huaweiapi": "*"}' | tee /usr/lib/abraflexi-reminder/composer.json
    cat /usr/lib/abraflexi-reminder/composer.json | jq '.repositories += [{"type":"path","url":"/usr/share/php/HuaweiApi/"}]' | tee /usr/lib/abraflexi-reminder/composer.json
    composer-debian abraflexi-reminder
fi

#DEBHELPER#

exit 0
