.TH "FlexiBee reminder" "1" "0.1.1" "Vítězslav Dvořák <info@vitexsoftware.cz>" "FlexiBee Reminder"
.SH "NAME"
php-flexibee-reminder - Sends reminders to debtors
.br
.SH "SYNTAX"
php-flexibee-reminder
.br

.SH "DESCRIPTION"
Show or modify php-flexibee configuration and setup labels in FlexiBee
.br
.br
.SH "FILES"
\fI/etc/\fRflexibee/reminder.json
\fI/etc/\fRflexibee/client.json
.br

.SH "AUTHORS"
Vítězslav Dvořák <info@vitexsoftware.cz>
.br

.SH "SEE ALSO"
php-flexibee-checker(1) php-flexibee-debts(1)
.br
