debian/conf/composer.json       usr/lib/abraflexi-reminder/
src/*.php           	        usr/share/abraflexi-reminder/

src/AbraFlexi/Reminder/*.php      usr/lib/abraflexi-reminder/Reminder/

src/AbraFlexi/Reminder/Notifier/ByEmail.php src/lib/abraflexi-reminder/Reminder/Notifier

bin/*  		usr/bin/
i18n/cs_CZ/LC_MESSAGES/*.mo     usr/share/locale/cs_CZ/LC_MESSAGES
i18n/en_US/LC_MESSAGES/*.mo     usr/share/locale/en_US/LC_MESSAGES
abraflexi-reminder.svg		usr/share/icons/hicolor/scalable/apps

debian/io.github.vitexsoftware.abraflexi_reminder.metainfo.xml   usr/share/metainfo/

.env				etc/abraflexi-reminder
