#!/bin/sh
# postinst script for flexibee-reminder
WEBUSER="root" 
set -e

    if [ "$1" = "configure" ]; then

    . /usr/share/debconf/confmodule

    fi

su - $WEBUSER -s /bin/bash -c 'COMPOSER_HOME="/var/lib/composer" composer  -o require listonoska/api -d /usr/lib/flexibee-reminder/'
su - $WEBUSER -s /bin/bash -c 'COMPOSER_HOME="/var/lib/composer" composer  -o require spipu/html2pdf -d /usr/lib/flexibee-reminder/'

#DEBHELPER#

exit 0
