debian/conf/composer.json       usr/lib/flexibee-reminder/
src/*.php           	        usr/lib/flexibee-reminder/
src/FlexiPeeHP/Reminder/*.php   usr/lib/flexibee-reminder/Reminder/
bin/*                           usr/bin/
debian/conf/reminder.json       etc/flexibee/
i18n/cs_CZ/LC_MESSAGES/*.mo     usr/share/locale/cs_CZ/LC_MESSAGES
i18n/en_US/LC_MESSAGES/*.mo     usr/share/locale/en_US/LC_MESSAGES
