#!/bin/bash
# rm script for flexibee-reminder-papermail

db_get composer/WEB_USER
WEBUSER=$RET

su - $WEBUSER -s /bin/bash -c 'COMPOSER_HOME="/var/lib/composer" composer -o remove listonoska/api -d /usr/lib/flexibee-reminder/'
su - $WEBUSER -s /bin/bash -c 'COMPOSER_HOME="/var/lib/composer" composer -o remove spipu/html2pdf -d /usr/lib/flexibee-reminder/'

rm /usr/lib/flexibee-reminder/composer.lock

#DEBHELPER#

exit 0
