bin/sshgnokiisms                           usr/bin

src/notifiers/BySms.php                    usr/lib/flexibee-reminder/notifiers

src/FlexiPeeHP/Reminder/SmsByAxfone.php    usr/lib/flexibee-reminder/Reminder/
src/FlexiPeeHP/Reminder/SmsByGnokii.php    usr/lib/flexibee-reminder/Reminder/
src/FlexiPeeHP/Reminder/SmsBySshGnokii.php usr/lib/flexibee-reminder/Reminder/
src/FlexiPeeHP/Reminder/Sms.php            usr/lib/flexibee-reminder/Reminder/
src/FlexiPeeHP/Reminder/SmsToAddress.php   usr/lib/flexibee-reminder/Reminder/

