#!/bin/sh
# postinst script for flexibee-reminder
WEBUSER="root" 
set -e

if [ "$1" = "configure" ]; then

    . /usr/share/debconf/confmodule

fi


mkdir -p /var/lib/composer
chown $WEBUSER:$WEBUSER /var/lib/composer
su - $WEBUSER -s /bin/bash -c 'COMPOSER_HOME="/var/lib/composer" composer -o install -d /usr/lib/flexibee-reminder/'

php -f /usr/lib/flexibee-reminder/init.php

#DEBHELPER#

exit 0
