debian/conf/composer.json       usr/lib/flexibee-reminder/
src/*.php           	        usr/lib/flexibee-reminder/

src/FlexiPeeHP/Reminder/Mailer.php      usr/lib/flexibee-reminder/Reminder/
src/FlexiPeeHP/Reminder/PDFPage.php     usr/lib/flexibee-reminder/Reminder/
src/FlexiPeeHP/Reminder/Upominac.php    usr/lib/flexibee-reminder/Reminder/
src/FlexiPeeHP/Reminder/Upominka.php    usr/lib/flexibee-reminder/Reminder/

src/FlexiPeeHP/Reminder/Notifier/ByEmail.php               usr/lib/flexibee-reminder/Reminder/Notifier

bin/flexibee-debts  		usr/bin/
bin/flexibee-inventarize  	usr/bin/
bin/flexibee-reminder		usr/bin/
bin/flexibee-reminder-init      usr/bin/
debian/conf/reminder.json       etc/flexibee/
i18n/cs_CZ/LC_MESSAGES/*.mo     usr/share/locale/cs_CZ/LC_MESSAGES
i18n/en_US/LC_MESSAGES/*.mo     usr/share/locale/en_US/LC_MESSAGES
