#!/bin/sh
# postinst script for php-flexibee-reminder
WEBUSER = "root" 
set -e

    if [ "$1" = "configure" ]; then

    . /usr/share/debconf/confmodule

    fi


mkdir -p /var/lib/composer
chown $WEBUSER:$WEBUSER /var/lib/composer
su - $WEBUSER -s /bin/bash -c 'COMPOSER_HOME="/var/lib/composer" composer --no-dev -o install -d /usr/share/php-flexibee-reminder/'

#DEBHELPER#

exit 0
