<?php

namespace Tests\FlexiPeeHP\Reminder;

use FlexiPeeHP\Reminder\Mailer;
/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-12-10 at 23:41:41.
 */
class MailerTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Mailer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Mailer;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers FlexiPeeHP\Reminder\Mailer::addItem
     * @todo   Implement testAddItem().
     */
    public function testAddItem()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FlexiPeeHP\Reminder\Mailer::getCss
     * @todo   Implement testGetCss().
     */
    public function testGetCss()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FlexiPeeHP\Reminder\Mailer::getCurrentMailSize
     * @todo   Implement testGetCurrentMailSize().
     */
    public function testGetCurrentMailSize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
