<?php

namespace Tests\FlexiPeeHP\Reminder;

use FlexiPeeHP\Reminder\PDFPage;
/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-12-10 at 23:41:42.
 */
class PDFPageTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var PDFPage
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PDFPage;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers FlexiPeeHP\Reminder\PDFPage::getPdf
     * @todo   Implement testGetPdf().
     */
    public function testGetPdf()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
