<?php

namespace Tests\FlexiPeeHP\Reminder;

use FlexiPeeHP\Reminder\Sms;
/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-12-10 at 23:41:42.
 */
class SmsTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Sms
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Sms;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers FlexiPeeHP\Reminder\Sms::getMessage
     * @todo   Implement testGetMessage().
     */
    public function testGetMessage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FlexiPeeHP\Reminder\Sms::getNumber
     * @todo   Implement testGetNumber().
     */
    public function testGetNumber()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FlexiPeeHP\Reminder\Sms::setNumber
     * @todo   Implement testSetNumber().
     */
    public function testSetNumber()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FlexiPeeHP\Reminder\Sms::setMessage
     * @todo   Implement testSetMessage().
     */
    public function testSetMessage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FlexiPeeHP\Reminder\Sms::unifyTelNo
     * @todo   Implement testUnifyTelNo().
     */
    public function testUnifyTelNo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FlexiPeeHP\Reminder\Sms::sendMessage
     * @todo   Implement testSendMessage().
     */
    public function testSendMessage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
